---
nvidia_driver_install_container: registry.cn-hangzhou.aliyuncs.com/esencloud/ubuntu-nvidia-driver-installer@sha256:eea7309dc4fa4a5c9d716157e74b90826e0a853aa26c7219db4710ddcd1ad8bc
nvidia_driver_install_supported: true
